'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { formatCurrencySSR } from '@/lib/utils/formatters';

export interface RFIDInvoiceLineItem {
  rfid_number: string;
  category: string;
  qty_washed: number;
  washes_remaining: number;
  price_per_wash: number;
  line_total: number;
}

export interface RFIDInvoiceData {
  invoice_number: string;
  invoice_date: string;
  location: string;
  generated_by: string;
  items: RFIDInvoiceLineItem[];
  subtotal: number;
  vat_amount: number;
  grand_total: number;
  total_items: number;
  category_breakdown: Array<{ category: string; count: number }>;
}

interface RFIDInvoiceProps {
  data: RFIDInvoiceData;
}

export default function RFIDInvoice({ data }: RFIDInvoiceProps) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>Invoice</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="flex items-start justify-between">
          <div className="space-y-1">
            <p className="text-slate-900 font-semibold">{data.location}</p>
            {data.generated_by && (
              <p className="text-sm text-slate-600">Generated by: {data.generated_by}</p>
            )}
          </div>
          <div className="text-right text-sm">
            <p className="text-slate-500">Invoice Number</p>
            <p className="font-medium">{data.invoice_number}</p>
            <p className="text-slate-500 mt-2">Invoice Date</p>
            <p className="font-medium">{data.invoice_date}</p>
          </div>
        </div>

        <div className="rounded-md border overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-slate-50 text-slate-700">
              <tr>
                <th className="text-left py-2 px-3">RFID Number</th>
                <th className="text-left py-2 px-3">Category</th>
                <th className="text-right py-2 px-3">QTY Washed</th>
                <th className="text-right py-2 px-3">Washes Remaining</th>
                <th className="text-right py-2 px-3">Price per wash</th>
                <th className="text-right py-2 px-3">Line Total</th>
              </tr>
            </thead>
            <tbody>
              {data.items.map((item, idx) => (
                <tr key={`${item.rfid_number}-${idx}`} className="border-t">
                  <td className="py-2 px-3">{item.rfid_number}</td>
                  <td className="py-2 px-3">{item.category}</td>
                  <td className="py-2 px-3 text-right">{item.qty_washed}</td>
                  <td className="py-2 px-3 text-right">{item.washes_remaining}</td>
                  <td className="py-2 px-3 text-right">{formatCurrencySSR(item.price_per_wash)}</td>
                  <td className="py-2 px-3 text-right">{formatCurrencySSR(item.line_total)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="space-y-1 text-sm max-w-sm ml-auto">
          <div className="flex items-center justify-between">
            <span className="text-slate-700">Subtotal</span>
            <span className="font-semibold">{formatCurrencySSR(data.subtotal)}</span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-slate-700">VAT (15%)</span>
            <span className="font-semibold">{formatCurrencySSR(data.vat_amount)}</span>
          </div>
          <div className="flex items-center justify-between pt-2 border-t">
            <span className="text-slate-900 font-medium">Grand Total (ZAR)</span>
            <span className="text-lg font-bold">{formatCurrencySSR(data.grand_total)}</span>
          </div>
        </div>

        <div className="pt-4 border-t">
          <p className="text-sm font-medium text-slate-700 mb-2">
            Total items processed: {data.total_items}
          </p>
          {data.category_breakdown.length > 0 && (
            <p className="text-sm text-slate-600">
              Breakdown by category: {data.category_breakdown.map((c) => `${c.category} × ${c.count}`).join(', ')}
            </p>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
